"""initial_schema

Revision ID: 3b527d7be7fb
Revises: 
Create Date: 2026-02-19 21:44:05.216119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b527d7be7fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_code', sa.String(length=32), nullable=False, comment='Unique slug used in the short URL path'),
    sa.Column('original_url', sa.Text(), nullable=False, comment='Full destination URL including scheme and query string'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-disable: False causes redirects to return 404'),
    sa.Column('is_custom_code', sa.Boolean(), server_default='false', nullable=False, comment='True when the caller explicitly chose the short_code'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of last modification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_links_is_active_created_at', 'links', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.create_table('click_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False, comment='FK to the short link that was clicked'),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the redirect request'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP (IPv4 max 15 chars, IPv6 max 45 chars)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Raw User-Agent header from the redirect request'),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_clicked_at'), 'click_events', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_click_events_link_id'), 'click_events', ['link_id'], unique=False)
    op.create_index('ix_click_events_link_id_clicked_at', 'click_events', ['link_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_click_events_link_id_clicked_at', table_name='click_events')
    op.drop_index(op.f('ix_click_events_link_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_clicked_at'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.drop_index('ix_links_is_active_created_at', table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
